name: Release

on:
    push

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Cache modules
              uses: actions/cache@v2
              with:
                  path: ~/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - name: Release
              if: matrix.platform == 'ubuntu-latest'
              uses: taiki-e/create-gh-release-action@v1
              with:
                  changelog: CHANGELOG.md
                  title: new
                  draft: false
              env:
                  GITHUB_TOKEN: ${{ secrets.github_token }}

            - run: npm install --save-dev 7zip-bin

            - run: npm run dist
              env:
                  GH_TOKEN: ${{ secrets.github_token }}
              